# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=244)),
                ('is_normalized', models.BooleanField(default=False)),
                ('normalized_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('string_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='overseer.String')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
            bases=('overseer.string',),
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('string_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='overseer.String')),
            ],
            bases=('overseer.string',),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('string_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='overseer.String')),
            ],
            bases=('overseer.string',),
        ),
    ]
